{% set name = "pyuvsim" %}
{% set version = "0.2.2" %}
{% set sha256 = "e32e0a765e4c60b6418bb8e97a0f85bb3abb3a7a03932d67ce35922130cbbfbf" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - astropy
    - mpi4py
    - numpy
    - pyuvdata
    - pyyaml
    - scipy
    - six
  run:
    - python
    - astropy
    - mpi4py
    - {{ pin_compatible('numpy') }}
    - pyuvdata
    - pyyaml
    - scipy
    - six

test:
  requires:
    - nose
  imports:
    - pyuvsim
  commands:
    - nosetests pyuvsim

about:
  home: https://github.com/RadioAstronomySoftwareGroup/pyuvsim
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A comprehensive simulation package for radio interferometers in python'
  doc_url: https://pyuvsim.readthedocs.io/
  dev_url: https://github.com/RadioAstronomySoftwareGroup/pyuvsim

extra:
  recipe-maintainers:
    - bhazelton
