{% set name = "pyuvsim" %}
{% set version = "0.2.3" %}
{% set sha256 = "85d54e00136d05e678a5c84cde5230edc839d0dfe3069202903eb45bd7ff8d07" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - astropy
    - mpi4py
    - numpy 1.14.*
    - pyuvdata
    - pyyaml
    - scipy
    - six
  run:
    - python
    - astropy
    - mpi4py
    - {{ pin_compatible('numpy') }}
    - pyuvdata
    - pyyaml
    - scipy
    - six

test:
  requires:
    - nose
  imports:
    - pyuvsim
  commands:
    - nosetests pyuvsim

about:
  home: https://github.com/RadioAstronomySoftwareGroup/pyuvsim
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A comprehensive simulation package for radio interferometers in python'
  doc_url: https://pyuvsim.readthedocs.io/
  dev_url: https://github.com/RadioAstronomySoftwareGroup/pyuvsim

extra:
  recipe-maintainers:
    - bhazelton
